(async function(){'use strict';
const C=RevizieCore,X=ExcelLocal,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let book,view='overview',tab='overdue',page=1,dirty=0,showInactive=false,activeDevice='',fileName='Ukážkové údaje',demo=true,indexes=new Map();
const labels={overdue:'Po termíne',soon:'Blíži sa termín',unknown:'Na overenie',ok:'V poriadku',inactive:'Neaktívna',event:'Pri udalosti',all:'Všetky kontroly'};
const format=v=>{const s=C.iso(v);return s?new Intl.DateTimeFormat('sk-SK').format(new Date(s+'T12:00:00')):'—';};
const rows=n=>book?.tables[n]?.rows||[];
const by=(n,key,id)=>{const k=n+':'+key;if(!indexes.has(k))indexes.set(k,new Map(rows(n).map(r=>[String(r[key]),r])));return indexes.get(k).get(String(id));};
const siteName=id=>by('Strediska','StrediskoID',id)?.Oznacenie||by('Strediska','StrediskoID',id)?.Nazov||id;
const kindName=p=>by('DruhyKontrol','DruhKontrolyID',p.DruhKontrolyID)?.Nazov||p.DruhKontrolyID;
const badge=s=>`<span class="badge ${s}">${labels[s]}</span>`;
const months=()=>Math.min(36,Math.max(1,Number($('months').value)||1));
const state=p=>C.status(p,by('Zariadenia','ZariadenieID',p.ZariadenieID),C.today(),months());
function toast(s){$('toast').textContent=s;$('toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('visible'),5500);}
function changed(){dirty++;$('dirty').textContent=`Neexportované zmeny: ${dirty}`;document.querySelector('.source-bar').classList.add('changed');}
function put(n,r,k,v){X.set(book,n,r,k,v);}
function baseDevices(){const q=$('search').value.toLocaleLowerCase('sk').trim();return rows('Zariadenia').filter(d=>(!$('site').value||d.StrediskoID===$('site').value)&&(!$('category').value||d.KategoriaID===$('category').value)&&(!q||[d.Nazov,d.ZariadenieID,d.EvidencneCislo,d.Umiestnenie,...rows('PlanKontrol').filter(p=>p.ZariadenieID===d.ZariadenieID).map(kindName)].join(' ').toLocaleLowerCase('sk').includes(q)));}
function plansFiltered(){const ids=new Set(baseDevices().map(d=>d.ZariadenieID));return rows('PlanKontrol').filter(p=>ids.has(p.ZariadenieID));}
function paginate(list){const pages=Math.max(1,Math.ceil(list.length/15));page=Math.min(page,pages);return {list:list.slice((page-1)*15,page*15),pages,total:list.length};}
function pager(p){return `<div class="pager"><span>${p.total?`${(page-1)*15+1}–${Math.min(page*15,p.total)} z ${p.total}`:'Žiadne záznamy'}</span><div><button data-page="-1" ${page===1?'disabled':''} aria-label="Predchádzajúca strana">←</button> &nbsp; ${page} / ${p.pages} &nbsp; <button data-page="1" ${page===p.pages?'disabled':''} aria-label="Ďalšia strana">→</button></div></div>`;}
function empty(s='Pre zvolené filtre nie sú žiadne záznamy.'){return `<div class="blank"><strong>Čistý prehľad</strong>${s}</div>`;}
function render(){if(!book)return;const titles={overview:['Prehľad revízií','Všetky dôležité termíny na jednom mieste.'],devices:['Zariadenia','Karty zariadení, technické údaje a kontrola podkladov.'],documents:['Dokumenty','Správy a prílohy evidované v načítanom zošite.'],help:['Ako to funguje','Jednoduchý postup od načítania až po uloženie zmien.']};
 $('title').textContent=titles[view][0];$('breadcrumb').textContent=titles[view][0];$('subtitle').textContent=titles[view][1];$('filters').hidden=['help','documents'].includes(view);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 if(view==='overview')renderOverview();if(view==='devices')renderDevices();if(view==='documents')renderDocs();if(view==='help')renderHelp();
}
function renderOverview(){const plans=plansFiltered(),count=s=>plans.filter(p=>state(p)===s).length;const data=plans.filter(p=>tab==='all'?(showInactive||state(p)!=='inactive'):state(p)===tab).sort((a,b)=>(C.iso(a.Termin)||'9999').localeCompare(C.iso(b.Termin)||'9999'));
 const p=paginate(data),end=format(C.addMonths(C.today(),months()));
 $('content').innerHTML=`<section class="kpis" aria-label="Súhrn kontrol">${[['overdue','Po termíne','Všetky omeškané kontroly','↗'],['soon','Blížiaci sa termín','Do '+end,'◷'],['unknown','Na overenie','Podklady, intervaly a termíny','?'],['devices','Zariadenia','Vo vybranom rozsahu','▤']].map(([s,l,h,i])=>`<button class="kpi ${s} ${tab===s?'active':''}" data-kpi="${s}"><span class="kpi-label">${l}<span class="kpi-icon">${i}</span></span><div class="kpi-number">${s==='devices'?baseDevices().length:count(s)}</div><small>${h}</small></button>`).join('')}</section>
 <div class="columns"><section class="panel"><div class="panel-head"><div><h2>Plán kontrol</h2><p>Jedna položka predstavuje jednu kontrolu zariadenia.</p></div>${tab==='all'?`<label class="check"><input id="inactive" type="checkbox" ${showInactive?'checked':''}> Aj neaktívne</label>`:'<span class="pill">Podľa termínu ↑</span>'}</div><div class="tab-row">${['overdue','soon','unknown','all'].map(s=>`<button class="tab ${tab===s?'active':''}" data-tab="${s}">${labels[s]}${s==='all'?'':' · '+count(s)}</button>`).join('')}</div>
 ${p.list.length?`<div class="table-wrap"><table><thead><tr><th>Zariadenie / kontrola</th><th>Stredisko</th><th>Termín</th><th>Stav</th></tr></thead><tbody>${p.list.map(plan=>{const d=by('Zariadenia','ZariadenieID',plan.ZariadenieID),s=state(plan),due=C.iso(plan.Termin),days=due?C.days(due,C.today()):null;return `<tr><td><button class="device-link" data-device="${esc(d.ZariadenieID)}">${esc(d.Nazov)}</button><small>${esc(kindName(plan))}</small><small class="id">${esc(d.ZariadenieID)}</small></td><td>${esc(siteName(d.StrediskoID))}</td><td class="date ${s}">${format(plan.Termin)}<small>${days===null?'Doplniť termín':days<0?`${-days} dní po termíne`:days===0?'Dnes':`O ${days} dní`}</small></td><td>${badge(s)}</td></tr>`;}).join('')}</tbody></table></div>`:empty(tab==='overdue'?'Vo vybranom rozsahu nie sú potvrdené kontroly po termíne. Skontroluj aj položky Na overenie.':undefined)}${pager(p)}</section>
 <aside class="stack"><section class="panel summary"><h2>Termíny podľa stredísk</h2><p>Po termíne a v zvolenom výhľade</p>${centreBars(plans)}<div class="legend"><span><i></i>Po termíne</span><span><i></i>Blížiace sa</span></div></section><section class="tip"><strong>Najprv skontroluj podklady</strong><p>Označenie <b>test</b> znamená, že fyzické dokumenty ešte neboli skontrolované.</p><p>Tieto záznamy nájdeš v prehľade <b>Na overenie</b>.</p><button class="text-button" data-tab="unknown">Zobraziť neoverené kontroly →</button></section></aside></div>`;
}
function centreBars(plans){const groups=rows('Strediska').map(s=>{const ps=plans.filter(p=>by('Zariadenia','ZariadenieID',p.ZariadenieID).StrediskoID===s.StrediskoID);return {s,red:ps.filter(p=>state(p)==='overdue').length,amber:ps.filter(p=>state(p)==='soon').length};}).filter(g=>g.red+g.amber>0).sort((a,b)=>b.red+b.amber-a.red-a.amber);const max=Math.max(1,...groups.map(g=>g.red+g.amber));return groups.length?groups.slice(0,10).map(g=>`<div class="bar-row"><div class="bar-text"><span>${esc(g.s.Nazov)}</span><b>${g.red+g.amber}</b></div><div class="bar-track"><span class="bar-red" style="width:${g.red/max*100}%"></span><span class="bar-amber" style="width:${g.amber/max*100}%"></span></div></div>`).join(''):'<p>V tomto rozsahu nie sú blížiace sa ani omeškané potvrdené kontroly.</p>';}
function renderDevices(){const p=paginate(baseDevices());$('content').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>Register zariadení</h2><p>Kliknutím na názov otvoríš kartu a súvisiace kontroly.</p></div><span class="pill">${p.total} zariadení</span></div>${p.list.length?`<div class="table-wrap"><table><thead><tr><th>Zariadenie</th><th>Stredisko</th><th>Umiestnenie</th><th>Podklady</th><th>Prevádzkový stav</th></tr></thead><tbody>${p.list.map(d=>`<tr><td><button class="device-link" data-device="${esc(d.ZariadenieID)}">${esc(d.Nazov)}</button><small class="id">${esc(d.ZariadenieID)}</small></td><td>${esc(siteName(d.StrediskoID))}</td><td>${esc(d.Umiestnenie||'—')}</td><td><span class="badge ${C.review(d)==='Skontrolovane'?'ok':'unknown'}">${{Skontrolovane:'Skontrolované',Neskontrolovane:'Neskontrolované',NaUpresnenie:'Na upresnenie'}[C.review(d)]||esc(C.review(d))}</span><small>Pôvodne: ${esc(d.PovodnyStav||'—')}</small></td><td>${esc({Vyradene:'Vyradené',VPrevadzke:'V prevádzke',MimoPrevadzky:'Mimo prevádzky',Neurceny:'Neurčený'}[d.PrevadzkovyStav]||d.PrevadzkovyStav||'Neurčený')}</td></tr>`).join('')}</tbody></table></div>`:empty()}${pager(p)}</section>`;}
function renderDocs(){const docs=rows('Dokumenty');$('content').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>Revízne správy a prílohy</h2><p>${docs.length} dokumentov v zošite</p></div><button class="button white" id="pdfBtn">Otvoriť lokálne PDF</button></div>${docs.length?`<div class="table-wrap"><table><thead><tr><th>Dokument</th><th>Číslo správy</th><th>Dátum</th><th>Cesta v úložisku</th></tr></thead><tbody>${docs.map(d=>`<tr><td>${esc(d.Nazov||d.DokumentID)}</td><td>${esc(d.CisloSpravy||'—')}</td><td>${format(d.DatumDokumentu)}</td><td class="document-path">${esc(d.Subor||'—')}</td></tr>`).join('')}</tbody></table></div>`:empty('Dokumenty zatiaľ nie sú pripojené. V tejto ukážke si môžeš otvoriť PDF zo svojho zariadenia.')}<div class="tip">Prepojenie na OneDrive zatiaľ nie je zapojené. Lokálne otvorenie PDF nepridá prílohu do evidencie ani ju nikam neodošle.</div></section>`;}
function renderHelp(){$('content').innerHTML=`<article class="panel help"><h2>1. Načítaj pripravený zošit</h2><p>Použi <b>Načítať Excel</b> a vyber súbor Revizie_AppSheet_zaklad_v01.xlsx. Ak je na OneDrive, najprv ho stiahni alebo vyber jeho lokálnu kópiu. Táto ukážka sa neprihlasuje do OneDrive.</p><h2>2. Vyber stredisko a výhľad</h2><p>Výhľad je 1 až 36 kalendárnych mesiacov. Kontroly po termíne zostávajú zobrazené bez ohľadu na výhľad. Vyhľadávanie pracuje s názvom, ID, evidenčným číslom, umiestnením a názvom kontroly.</p><h2>3. Pracuj s kartou zariadenia</h2><p>Otvor názov zariadenia. Môžeš upraviť názov, umiestnenie, kontrolu podkladov, prevádzkový stav a poznámku. Každá kontrola má vlastný termín a overenie. Nová revízia pribudne do histórie. Starší historický zápis neprepíše aktuálny termín.</p><h2>Čo znamená Na overenie?</h2><p>Sem patria neskontrolované podklady (pôvodné <b>test</b>), neoverené kontroly, chýbajúce dátumy a nejasné intervaly. Skontrolované podklady neznamenajú automaticky platnú revíziu. Vyradené zariadenia a nevyžadované kontroly sa nezapočítajú do potvrdených omeškaní.</p><h2>4. Exportuj zmeny</h2><p><b>Exportovať Excel</b> stiahne nový súbor. Ten následne sám uložíš na OneDrive. Pri načítanom zošite aplikácia zachová ostatné hárky a upraví zmenené bunky. PDF súbory nie sú súčasťou exportu.</p><h2>Kde sú údaje?</h2><p>Načítaný Excel je iba v pamäti tejto otvorenej stránky. Zatvorením alebo obnovením stránky neexportované zmeny stratíš. Mobilný prehliadač môže stránku ukončiť aj na pozadí, preto priebežne exportuj. Ukážka nepoužíva automatické zálohovanie, zdieľanú databázu ani prihlasovanie.</p><h2>Ukážka na GitHub Pages</h2><p>Do repozitára patrí iba kód aplikácie z pripraveného balíka. Svoj Excel a firemné PDF doň nenahrávaj. Fiktívne ukážkové dáta slúžia iba na vyskúšanie ovládania.</p></article>`;}
function option(v,label,current){return `<option value="${esc(v)}" ${v===current?'selected':''}>${esc(label)}</option>`;}
function openDevice(id){activeDevice=id;const d=by('Zariadenia','ZariadenieID',id),plans=rows('PlanKontrol').filter(p=>p.ZariadenieID===id),rs=rows('Revizie').filter(r=>plans.some(p=>p.PlanID===r.PlanID)).sort((a,b)=>(C.iso(b.DatumVykonania)||'').localeCompare(C.iso(a.DatumVykonania)||''));
 const params=rows('ParametreZariadeni').filter(r=>r.ZariadenieID===id);
 $('detailBody').innerHTML=`<div class="dialog-head"><div><small>${esc(siteName(d.StrediskoID))} / ${esc(id)}</small><h2>${esc(d.Nazov)}</h2></div><button class="close" id="closeDetail" aria-label="Zavrieť kartu">×</button></div><div class="dialog-body"><h3>Základné údaje</h3><form id="deviceForm"><div class="form-grid"><label class="wide">Názov zariadenia<input name="Nazov" value="${esc(d.Nazov)}" required></label><label>Umiestnenie<input name="Umiestnenie" value="${esc(d.Umiestnenie)}"></label><label>Kontrola fyzických podkladov<select name="KontrolaPodkladov">${[['Neskontrolovane','Neskontrolované'],['Skontrolovane','Skontrolované'],['NaUpresnenie','Na upresnenie']].map(x=>option(...x,C.review(d))).join('')}</select></label><label>Prevádzkový stav<select name="PrevadzkovyStav">${[['Neurceny','Neurčený'],['VPrevadzke','V prevádzke'],['MimoPrevadzky','Mimo prevádzky'],['Vyradene','Vyradené']].map(x=>option(...x,d.PrevadzkovyStav||'Neurceny')).join('')}</select></label><label>Pôvodné označenie<input value="${esc(d.PovodnyStav||'—')}" readonly aria-readonly="true"></label><label class="wide">Poznámka<textarea name="Poznamka" rows="2">${esc(d.Poznamka)}</textarea></label></div><button class="button primary" type="submit">Uložiť údaje v ukážke</button><p class="inline-note">Trvalé uloženie vykonáš exportom Excelu. Overenie termínov nastav samostatne pri kontrolách.</p></form>
 <details><summary>Identifikácia a technické parametre <span class="pill">${params.length} parametrov</span></summary><div class="plan-inner"><div class="form-grid">${[['Evidenčné číslo',d.EvidencneCislo],['Typ',d.TypoveOznacenie],['Výrobca',d.Vyrobca],['Výrobné číslo',d.VyrobneCislo],['Rok výroby',d.RokVyroby],['Skupina',d.Skupina],...params.map(p=>[by('DefinicieParametrov','ParameterID',p.ParameterID)?.Nazov||p.ParameterID,p.Hodnota])].map(([k,v])=>`<div><small>${esc(k)}</small><div>${esc(v||'—')}</div></div>`).join('')}</div></div></details>
 <div class="section-title"><h3>Kontroly zariadenia</h3><span>${plans.length} kontrol</span></div>${plans.map(plan=>`<details ${plans.length===1?'open':''}><summary>${esc(kindName(plan))} ${badge(state(plan))}</summary><div class="plan-inner"><form class="planForm" data-plan="${esc(plan.PlanID)}"><p class="inline-note">Režim: ${esc(plan.Rezim)}${plan.Poznamka?' · '+esc(plan.Poznamka):''}</p><div class="form-grid"><label>Nasledujúci termín<input type="date" name="Termin" value="${C.iso(plan.Termin)}"></label><label>Overenie kontroly<select name="Overenie">${[['Overene','Overená podľa podkladov'],['Neoverene','Neoverená'],['NaOverenie','Na overenie']].map(x=>option(...x,plan.Overenie)).join('')}</select></label>${plan.Rezim==='Pravidelna'?`<label>Interval (${plan.IntervalJednotka==='Den'?'dni':'mesiace'})<input type="number" min="1" max="1200" step="1" name="IntervalHodnota" value="${esc(plan.IntervalHodnota)}" required></label>`:''}</div><div class="plan-actions"><button class="button white" type="submit">Uložiť termín</button><button class="button primary" type="button" data-newrev="${esc(plan.PlanID)}">＋ Zapísať revíziu</button></div></form><div id="rev-${esc(plan.PlanID)}"></div></div></details>`).join('')||'<p class="inline-note">Zariadenie nemá evidované kontroly.</p>'}
 <div class="section-title"><h3>História revízií</h3><span>${rs.length} záznamov</span></div>${rs.length?`<div class="table-wrap"><table class="history"><thead><tr><th>Dátum</th><th>Kontrola</th><th>Výsledok</th><th>Pôvod</th></tr></thead><tbody>${rs.map(r=>`<tr><td class="date">${format(r.DatumVykonania)}</td><td>${esc(kindName(by('PlanKontrol','PlanID',r.PlanID)))}</td><td>${esc(r.Vysledok||'Nezadaný')}${r.Zrusena?'<small>Zrušený zápis</small>':''}</td><td>${esc(r.PovodZaznamu==='ImportPoslednehoDatumu'?'Import posledného dátumu':r.PovodZaznamu==='NovaRevizia'?'Nový zápis':'Ukážkový zápis')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="inline-note">Zatiaľ bez dátumu vykonanej revízie.</p>'}</div>`;
 if(!$('detail').open)$('detail').showModal();
}
function newRevision(pid){const p=by('PlanKontrol','PlanID',pid);$('rev-'+pid).innerHTML=`<form class="revision-form" data-plan="${esc(pid)}"><h3>Nová vykonaná revízia</h3><div class="form-grid"><label>Dátum vykonania<input type="date" name="DatumVykonania" value="${C.today()}" max="${C.today()}" required></label><label>Výsledok<select name="Vysledok" required><option value="">Vyber výsledok</option>${['Vyhovuje','VyhovujeSZavadami','Nevyhovuje','Nezadany'].map((v,i)=>option(v,['Vyhovuje','Vyhovuje so závadami','Nevyhovuje','Výsledok nie je uvedený'][i],'')).join('')}</select></label><label>Nasledujúci termín<input type="date" name="NasledujuciTermin" value="${C.next(C.today(),p)}" ${p.Rezim==='Pravidelna'?'required':''}></label><label>Technik<input name="Technik"></label><label class="wide">Poznámka<textarea name="Poznamka" rows="2"></textarea></label></div><p class="inline-note">Navrhnutý termín vychádza z intervalu. Over ho podľa správy. Starší historický zápis nezmení aktuálny plán.</p><button class="button primary" type="submit">Pridať do histórie</button></form>`;}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.view){view=b.dataset.view;page=1;render();}
 if(b.dataset.tab){view='overview';tab=b.dataset.tab;page=1;render();}
 if(b.dataset.kpi){if(b.dataset.kpi==='devices')view='devices';else{tab=b.dataset.kpi;view='overview';}page=1;render();}
 if(b.dataset.page){page+=Number(b.dataset.page);render();}
 if(b.dataset.device)openDevice(b.dataset.device);
 if(b.dataset.newrev)newRevision(b.dataset.newrev);
 if(b.id==='closeDetail')$('detail').close();
 if(b.id==='pdfBtn')$('pdf').click();
});
document.addEventListener('change',e=>{if(e.target.id==='inactive'){showInactive=e.target.checked;page=1;render();}
 if(e.target.name==='DatumVykonania'&&e.target.closest('.revision-form')){const f=e.target.form,p=by('PlanKontrol','PlanID',f.dataset.plan);if(C.iso(e.target.value))f.elements.NasledujuciTermin.value=C.next(e.target.value,p);}
});
document.addEventListener('submit',e=>{if(!e.target.closest('#detail'))return;e.preventDefault();const f=e.target,data=Object.fromEntries(new FormData(f));try{
 if(f.id==='deviceForm'){const d=by('Zariadenia','ZariadenieID',activeDevice);for(const [k,v]of Object.entries(data)){const field=k==='KontrolaPodkladov'&&!book.tables.Zariadenia.headers.includes(k)?'OverenieUdajov':k;const value=field==='OverenieUdajov'?({Skontrolovane:'Overene',Neskontrolovane:'Neoverene',NaUpresnenie:'NaOverenie'}[v]):v;put('Zariadenia',d,field,value);}changed();openDevice(activeDevice);render();toast('Údaje upravené. Pre trvalé uloženie exportuj Excel.');}
 if(f.classList.contains('planForm')){const p=by('PlanKontrol','PlanID',f.dataset.plan);put('PlanKontrol',p,'Termin',data.Termin?C.serial(data.Termin):'');put('PlanKontrol',p,'Overenie',data.Overenie);if(data.IntervalHodnota)put('PlanKontrol',p,'IntervalHodnota',Number(data.IntervalHodnota));changed();openDevice(activeDevice);render();toast('Termín upravený. Zmena čaká na export.');}
 if(f.classList.contains('revision-form')){const p=by('PlanKontrol','PlanID',f.dataset.plan);if(data.NasledujuciTermin&&data.NasledujuciTermin<data.DatumVykonania)throw Error('Nasledujúci termín nemôže byť pred vykonaním revízie.');const latest=rows('Revizie').filter(r=>r.PlanID===p.PlanID&&!r.Zrusena).map(r=>C.iso(r.DatumVykonania)).sort().at(-1)||'';
  X.append(book,'Revizie',{ReviziaID:'REV_'+crypto.randomUUID(),PlanID:p.PlanID,DatumVykonania:C.serial(data.DatumVykonania),Vysledok:data.Vysledok,DodavatelID:'',Technik:data.Technik,NasledujuciTermin:data.NasledujuciTermin?C.serial(data.NasledujuciTermin):'',Overenie:'Overene',PovodZaznamu:'NovaRevizia',Poznamka:data.Poznamka,ZapisalEmail:'',ZapisaneDna:Date.now()/86400000+25569,Zrusena:false});
  if(data.DatumVykonania>=latest){put('PlanKontrol',p,'Termin',data.NasledujuciTermin?C.serial(data.NasledujuciTermin):'');put('PlanKontrol',p,'Overenie','Overene');}
  changed();openDevice(activeDevice);render();toast(data.DatumVykonania>=latest?'Revízia pridaná a aktuálny plán upravený. Exportuj Excel.':'Historická revízia pridaná. Aktuálny termín zostal zachovaný.');
 }
 }catch(err){toast(err.message);}});
function loadUI(){indexes.clear();$('site').innerHTML='<option value="">Všetky strediská</option>'+rows('Strediska').map(s=>option(s.StrediskoID,s.Oznacenie||s.Nazov,'')).join('');$('category').innerHTML='<option value="">Všetky kategórie</option>'+rows('Kategorie').map(c=>option(c.KategoriaID,c.Nazov,'')).join('');$('search').value='';page=1;dirty=0;view='overview';tab='overdue';$('sourceName').textContent=fileName;$('sourceHint').textContent=demo?'Fiktívne zariadenia. Načítaj svoj súbor a pokračuj.':`${rows('Zariadenia').length} zariadení · ${rows('PlanKontrol').length} kontrol · iba v tomto prehliadači`;$('dirty').textContent='Bez zmien';document.querySelector('.source-bar').classList.remove('changed');render();}
async function loadDemo(){book=await X.fromTables(C.demo());C.validate(book.tables);fileName='Ukážkové údaje';demo=true;loadUI();}
$('importBtn').onclick=()=>$('file').click();
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;try{if(!/\.xlsx$/i.test(f.name))throw Error('Vyber zošit vo formáte .xlsx bez makier.');if(f.size>20*1024*1024)throw Error('Pre ukážku vyber súbor menší než 20 MB.');if(dirty&&!confirm('Neexportované zmeny sa načítaním iného súboru stratia. Pokračovať?'))return;$('importBtn').disabled=true;$('importBtn').textContent='Načítavam…';const candidate=await X.read(await f.arrayBuffer());C.validate(candidate.tables);book=candidate;demo=false;fileName=f.name;loadUI();toast('Excel načítaný. Údaje zostali v tvojom prehliadači.');}catch(err){toast('Načítanie zlyhalo: '+err.message);}finally{$('file').value='';$('importBtn').disabled=false;$('importBtn').textContent='↥ Načítať Excel';}};
$('exportBtn').onclick=async()=>{try{$('exportBtn').disabled=true;const bytes=await X.write(book);const url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download=`${demo?'Revizie_ukazka':fileName.replace(/\.xlsx$/i,'')}_upravy_${C.today()}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);dirty=0;$('dirty').textContent='Export pripravený';document.querySelector('.source-bar').classList.remove('changed');toast('Excel pripravený na stiahnutie. Ulož ho na svoj OneDrive.');}catch(err){toast('Export zlyhal: '+err.message);}finally{$('exportBtn').disabled=false;}};
$('demoBtn').onclick=async()=>{if(dirty&&!confirm('Neexportované zmeny sa stratia. Obnoviť fiktívnu ukážku?'))return;await loadDemo();};
for(const id of ['site','category','months'])$(id).addEventListener('change',()=>{if(id==='months')$('months').value=months();page=1;render();});$('search').addEventListener('input',()=>{page=1;render();});
$('pdf').onchange=()=>{const f=$('pdf').files[0];if(!f)return;const url=URL.createObjectURL(f);const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.click();setTimeout(()=>URL.revokeObjectURL(url),300000);$('pdf').value='';};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
$('today').textContent=new Intl.DateTimeFormat('sk-SK',{day:'numeric',month:'long',year:'numeric'}).format(new Date());
document.querySelector('.brand').onclick=e=>{e.preventDefault();view='overview';render();};
try{await loadDemo();}catch(err){$('content').innerHTML='<div class="blank error">Ukážku sa nepodarilo načítať. Skús obnoviť stránku.</div>';console.error(err);}
})();
